name: Solar System Workflow

on:
  push:
    branches:
      - main
      - 'feat/*'

env:
  MONGO_URI: 'mongodb+srv://cluster0.9inhs2g.mongodb.net/superdata'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
        matrix:
            node-version: [18, 19, 20]
            operating-system: [ubuntu-latest, windows-latest]
            exclude:
                - node-version: 18
                  operating-system: ubuntu-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Archive test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Report
          path: test-results.xml