name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feat/*'

env:
  MONGO_URI: 'mongodb+srv://cluster0.9inhs2g.mongodb.net/superdata'
  REGISTRY_LOGIN_SERVER: ghacr-caagerfsb6dtg6e3.azurecr.io
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    services:
      mongo:
        image: siddharth67/mongo-db:non-prod
        ports:
        - 27017:27017
    env:
        MONGO_URI: 'mongodb://localhost:27017/superData'
        MONGO_USERNAME: non-prod-user
        MONGO_PASSWORD: non-prod-password
    strategy:
        matrix:
            node-version: [18]
            operating-system: [ubuntu-latest]
            # exclude:
            #     - node-version: 20
            #       operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: npm_test
        run: npm test

      - name: Archive test report
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Report-${{ matrix.operating-system }}-Node-${{ matrix.node-version }}
          path: test-results.xml
    
  code-coverage:
    name: Code Coverage
    container:
      image: node:18
    services:
      mongo:
        image: siddharth67/mongo-db:non-prod
        options: --name mongo
    env:
        MONGO_URI: 'mongodb://mongo:27017/superData'
        MONGO_USERNAME: non-prod-user
        MONGO_PASSWORD: non-prod-password
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    #   - name: Set up Node.js - 18
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: '18'

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }} 

      - name: Install dependencies
        run: npm install

      - name: Run code coverage
        continue-on-error: true
        run: npm run coverage

      - name: Upload artifacts - Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Report
          path: coverage
          retention-days: 5

  docker-build-and-push:
    name: Docker Build and Push to ACR
    needs: [unit-testing, code-coverage]
    runs-on: ubuntu-latest
    permissions:
        packages: write
        id-token: write
        contents: read
    steps:
      - name: Azure login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: GHCR login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build for Testing
        uses: docker/build-push-action@v5
        with:
            push: false
            tags: ${{ env.REGISTRY_LOGIN_SERVER }}/solar-system:${{ github.sha }}
            file: Dockerfile
      
      - name: Docker Image Test
        run: |
          docker images
          docker run --name solar-system-app -d -p 3000:3000 \
            -e MONGO_URI=${{ env.MONGO_URI }} \
            -e MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
            -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            ${{ env.REGISTRY_LOGIN_SERVER }}/solar-system:${{ github.sha }}

          echo "Testing Image URL using wget"
          wget -q -O - 127.0.0.1:3000/live | grep live

      - name: Container Registry Push
        uses: docker/build-push-action@v5
        with:
            push: true
            file: Dockerfile
            tags: |
                ${{ env.REGISTRY_LOGIN_SERVER }}/solar-system:${{ github.sha }}
                ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
  
  dev-deploy:
    name: Dev Deploy
    if: contains(github.ref, 'feat/')
    needs: docker-build-and-push
    uses: ./.github/workflows/reuse-deployment.yml
    secrets: 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
  dev-integration-testing:
    name: Dev Integration Testing
    if: contains(github.ref, 'feat/')
    needs: dev-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test URL Output
        env:
          APP_INGRESS_HOST: ${{ needs.dev-deploy.outputs.APP_INGRESS_HOST }}
        run: |
          echo "Application URL: http://${{ env.APP_INGRESS_HOST }}"
          echo "--------------------------------------"
          curl https://${{ env.APP_INGRESS_HOST }}/live -s -k | jq -r .status | grep -i live

  prod-deploy:
    name: Prod Deploy
    if: github.ref == 'refs/heads/main'
    needs: docker-build-and-push
    uses: ./.github/workflows/reuse-deployment.yml
    
  prod-integration-testing:
    name: Prod Integration Testing
    if: github.ref == 'refs/heads/main'
    needs: prod-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test URL Output
        env:
          APP_INGRESS_HOST: ${{ needs.prod-deploy.outputs.APP_INGRESS_HOST }}
        run: |
          echo "Application URL: http://${{ env.APP_INGRESS_HOST }}"
          echo "--------------------------------------"
          curl https://${{ env.APP_INGRESS_HOST }}/live -s -k | jq -r .status | grep -i live